--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.4

-- Started on 2025-11-12 12:43:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 3079 OID 66392)
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- TOC entry 3735 (class 0 OID 0)
-- Dependencies: 3
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- TOC entry 2 (class 3079 OID 40939)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 3736 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- TOC entry 260 (class 1255 OID 40950)
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: resume_wrangler_user
--

CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at() OWNER TO resume_wrangler_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 40951)
-- Name: applications; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.applications (
    id bigint NOT NULL,
    posting_text text,
    is_complete text DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    date_submitted timestamp with time zone,
    job_position text,
    posting_url text,
    analyzed_posting_text text,
    company_id bigint,
    key_skills text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    location text
);


ALTER TABLE public.applications OWNER TO resume_wrangler_user;

--
-- TOC entry 3737 (class 0 OID 0)
-- Dependencies: 217
-- Name: TABLE applications; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.applications IS 'Table of job applications';


--
-- TOC entry 218 (class 1259 OID 40959)
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 40960)
-- Name: body_fonts; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.body_fonts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.body_fonts OWNER TO resume_wrangler_user;

--
-- TOC entry 220 (class 1259 OID 40968)
-- Name: companies; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    address_one text,
    address_two text,
    recipient_title text,
    email text,
    phone text,
    website_url text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.companies OWNER TO resume_wrangler_user;

--
-- TOC entry 3738 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE companies; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.companies IS 'Table of companies';


--
-- TOC entry 221 (class 1259 OID 40975)
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 40976)
-- Name: cover_experience_lines; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.cover_experience_lines (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cover_letter_id bigint NOT NULL,
    cover_experience_id bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    "position" text,
    line_type text
);


ALTER TABLE public.cover_experience_lines OWNER TO resume_wrangler_user;

--
-- TOC entry 223 (class 1259 OID 40982)
-- Name: cover_experiences; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.cover_experiences (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    description text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.cover_experiences OWNER TO resume_wrangler_user;

--
-- TOC entry 3739 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE cover_experiences; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.cover_experiences IS 'Table of cover letter experiences';


--
-- TOC entry 224 (class 1259 OID 40989)
-- Name: cover_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.cover_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cover_experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 41300)
-- Name: cover_letter_templates; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.cover_letter_templates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text,
    thumbnail_url text,
    cloudinary_public_id text,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    active text
);


ALTER TABLE public.cover_letter_templates OWNER TO resume_wrangler_user;

--
-- TOC entry 225 (class 1259 OID 40990)
-- Name: cover_letters; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.cover_letters (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    company_id bigint,
    first_name text DEFAULT 'Josh'::text,
    last_name text DEFAULT 'Lehman'::text,
    recipient_title text DEFAULT 'Software Team Hiring Manager'::text,
    intro_text_start text DEFAULT 'Attached is a copy of my resume in response to the job posting for: '::text,
    intro_skills text,
    intro_experience text,
    application_id bigint,
    intro_text_end text DEFAULT 'This role appears to be an exciting opportunity where my skill set would prove to be a valuable addition to your company.'::text,
    salutation_text text DEFAULT 'Regards'::text,
    conclusion_text text DEFAULT 'In addition to the skills mentioned above, I have a solid educational foundation which includes a Bachelor’s Degree in Engineering Technology from McMaster University and an Advanced Diploma in Engineering Technology from Mohawk College.'::text,
    thanks_text text DEFAULT 'Thank you for your time and consideration.'::text,
    user_id uuid,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    template text DEFAULT 'standard'::text NOT NULL,
    heading_font text DEFAULT 'font-raleway-bold'::text NOT NULL,
    body_font text DEFAULT 'font-quicksand'::text NOT NULL,
    color text DEFAULT 'bg-white'::text NOT NULL,
    highlight_color text DEFAULT 'bg-white'::text NOT NULL
);


ALTER TABLE public.cover_letters OWNER TO resume_wrangler_user;

--
-- TOC entry 3740 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE cover_letters; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.cover_letters IS 'Table of cover letters';


--
-- TOC entry 226 (class 1259 OID 41007)
-- Name: cover_letters_cover_letter_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.cover_letters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cover_letters_cover_letter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 41008)
-- Name: header_fonts; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.header_fonts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.header_fonts OWNER TO resume_wrangler_user;

--
-- TOC entry 248 (class 1259 OID 66216)
-- Name: pgmigrations; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.pgmigrations (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    run_on timestamp without time zone NOT NULL
);


ALTER TABLE public.pgmigrations OWNER TO resume_wrangler_user;

--
-- TOC entry 247 (class 1259 OID 66215)
-- Name: pgmigrations_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

CREATE SEQUENCE public.pgmigrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pgmigrations_id_seq OWNER TO resume_wrangler_user;

--
-- TOC entry 3741 (class 0 OID 0)
-- Dependencies: 247
-- Name: pgmigrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: resume_wrangler_user
--

ALTER SEQUENCE public.pgmigrations_id_seq OWNED BY public.pgmigrations.id;


--
-- TOC entry 228 (class 1259 OID 41016)
-- Name: resume_colors; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resume_colors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text,
    color text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    highlight_color text
);


ALTER TABLE public.resume_colors OWNER TO resume_wrangler_user;

--
-- TOC entry 229 (class 1259 OID 41024)
-- Name: resume_experiences; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resume_experiences (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    company text,
    detail text,
    date text,
    description text,
    type text,
    link_url text,
    git_url text,
    user_id uuid NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.resume_experiences OWNER TO resume_wrangler_user;

--
-- TOC entry 3742 (class 0 OID 0)
-- Dependencies: 229
-- Name: TABLE resume_experiences; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.resume_experiences IS 'Table of resume experiences';


--
-- TOC entry 230 (class 1259 OID 41031)
-- Name: resume_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resume_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 41032)
-- Name: resume_experiences_template; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resume_experiences_template (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    company text,
    detail text,
    date text,
    description text,
    type text,
    link_url text,
    git_url text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.resume_experiences_template OWNER TO resume_wrangler_user;

--
-- TOC entry 232 (class 1259 OID 41039)
-- Name: resume_experiences_template_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resume_experiences_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_experiences_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 41040)
-- Name: resume_lines; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resume_lines (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "position" text,
    resume_id bigint NOT NULL,
    line_type text,
    user_education_id uuid,
    work_experience_id uuid,
    user_skills_id uuid,
    user_custom_section_one_id uuid,
    user_custom_section_two_id uuid
);


ALTER TABLE public.resume_lines OWNER TO resume_wrangler_user;

--
-- TOC entry 3743 (class 0 OID 0)
-- Dependencies: 233
-- Name: TABLE resume_lines; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.resume_lines IS 'Resume experience lines';


--
-- TOC entry 234 (class 1259 OID 41048)
-- Name: resume_templates; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resume_templates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text,
    thumbnail_url text,
    cloudinary_public_id text,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    active text DEFAULT 'false'::text NOT NULL
);


ALTER TABLE public.resume_templates OWNER TO resume_wrangler_user;

--
-- TOC entry 235 (class 1259 OID 41057)
-- Name: resumes; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.resumes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    company_id text,
    title text,
    template text,
    color text,
    heading_font text DEFAULT 'font-raleway-bold'::text NOT NULL,
    body_font text DEFAULT 'font-quicksand'::text NOT NULL,
    show_social_icons text DEFAULT true NOT NULL,
    show_skill_progress text DEFAULT true NOT NULL,
    show_skills_section text DEFAULT true NOT NULL,
    show_education_section text DEFAULT true NOT NULL,
    show_custom_section_one text DEFAULT true NOT NULL,
    custom_section_one_name text DEFAULT 'Organizations'::text NOT NULL,
    show_custom_section_two text DEFAULT true NOT NULL,
    custom_section_two_name text DEFAULT 'Certifications'::text NOT NULL,
    description text,
    highlight_color text,
    show_user_image text DEFAULT false NOT NULL
);


ALTER TABLE public.resumes OWNER TO resume_wrangler_user;

--
-- TOC entry 3744 (class 0 OID 0)
-- Dependencies: 235
-- Name: TABLE resumes; Type: COMMENT; Schema: public; Owner: resume_wrangler_user
--

COMMENT ON TABLE public.resumes IS 'Table of resumes';


--
-- TOC entry 236 (class 1259 OID 41073)
-- Name: resumes_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 41074)
-- Name: selected_application; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.selected_application (
    id bigint NOT NULL,
    application_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.selected_application OWNER TO resume_wrangler_user;

--
-- TOC entry 238 (class 1259 OID 41079)
-- Name: selected_application_id_seq; Type: SEQUENCE; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.selected_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.selected_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 66499)
-- Name: user_accounts; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_account_id text NOT NULL,
    access_token text,
    refresh_token text,
    expires_at timestamp with time zone,
    scope text,
    token_type text,
    id_token text,
    profile_json jsonb,
    profile_name text,
    profile_email text,
    profile_picture text,
    last_signin_at timestamp with time zone,
    revoked boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.user_accounts OWNER TO resume_wrangler_user;

--
-- TOC entry 239 (class 1259 OID 41080)
-- Name: user_custom_section_one; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_custom_section_one (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    location text,
    start_date text,
    end_date text,
    description text
);


ALTER TABLE public.user_custom_section_one OWNER TO resume_wrangler_user;

--
-- TOC entry 240 (class 1259 OID 41088)
-- Name: user_custom_section_two; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_custom_section_two (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    location text,
    start_date text,
    end_date text,
    description text
);


ALTER TABLE public.user_custom_section_two OWNER TO resume_wrangler_user;

--
-- TOC entry 241 (class 1259 OID 41096)
-- Name: user_education; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_education (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    institution_name text NOT NULL,
    program text,
    url text,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    location text,
    start_date text,
    description_one text,
    description_two text,
    description_three text,
    end_date text,
    grade text
);


ALTER TABLE public.user_education OWNER TO resume_wrangler_user;

--
-- TOC entry 242 (class 1259 OID 41104)
-- Name: user_skills; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_skills (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    skill text NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    skill_level text
);


ALTER TABLE public.user_skills OWNER TO resume_wrangler_user;

--
-- TOC entry 243 (class 1259 OID 41112)
-- Name: user_work_experience; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.user_work_experience (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    job_title text NOT NULL,
    company_name text,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    location text,
    description_one text,
    description_two text,
    description_three text,
    description_four text,
    start_date text,
    end_date text
);


ALTER TABLE public.user_work_experience OWNER TO resume_wrangler_user;

--
-- TOC entry 244 (class 1259 OID 41120)
-- Name: users; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    email text NOT NULL,
    password text,
    first_name text,
    last_name text,
    address_one text,
    address_two text,
    address_three text,
    phone text,
    website text,
    thumbnail text,
    linked_in text,
    twitter text,
    facebook text,
    instagram text,
    github text,
    country text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    new_user text DEFAULT true NOT NULL,
    access_level text DEFAULT 'basic'::text NOT NULL,
    tour_dashboard text DEFAULT 'true'::text NOT NULL
);


ALTER TABLE public.users OWNER TO resume_wrangler_user;

--
-- TOC entry 245 (class 1259 OID 41277)
-- Name: views; Type: TABLE; Schema: public; Owner: resume_wrangler_user
--

CREATE TABLE public.views (
    slug character varying(255) NOT NULL,
    count integer NOT NULL
);


ALTER TABLE public.views OWNER TO resume_wrangler_user;

--
-- TOC entry 3446 (class 2604 OID 66219)
-- Name: pgmigrations id; Type: DEFAULT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.pgmigrations ALTER COLUMN id SET DEFAULT nextval('public.pgmigrations_id_seq'::regclass);


--
-- TOC entry 3452 (class 2606 OID 41131)
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- TOC entry 3462 (class 2606 OID 41133)
-- Name: body_fonts body_fonts_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.body_fonts
    ADD CONSTRAINT body_fonts_pkey PRIMARY KEY (id);


--
-- TOC entry 3478 (class 2606 OID 41135)
-- Name: resume_colors colors_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_colors
    ADD CONSTRAINT colors_pkey PRIMARY KEY (id);


--
-- TOC entry 3464 (class 2606 OID 41137)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- TOC entry 3469 (class 2606 OID 41321)
-- Name: cover_experience_lines cover_experience_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_experience_lines
    ADD CONSTRAINT cover_experience_lines_pkey PRIMARY KEY (id);


--
-- TOC entry 3471 (class 2606 OID 41141)
-- Name: cover_experiences cover_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_experiences
    ADD CONSTRAINT cover_experiences_pkey PRIMARY KEY (id);


--
-- TOC entry 3526 (class 2606 OID 41309)
-- Name: cover_letter_templates cover_letter_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_letter_templates
    ADD CONSTRAINT cover_letter_templates_pkey PRIMARY KEY (id);


--
-- TOC entry 3474 (class 2606 OID 41143)
-- Name: cover_letters cover_letters_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_letters
    ADD CONSTRAINT cover_letters_pkey PRIMARY KEY (id);


--
-- TOC entry 3476 (class 2606 OID 41145)
-- Name: header_fonts header_fonts_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.header_fonts
    ADD CONSTRAINT header_fonts_pkey PRIMARY KEY (id);


--
-- TOC entry 3528 (class 2606 OID 66221)
-- Name: pgmigrations pgmigrations_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.pgmigrations
    ADD CONSTRAINT pgmigrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3481 (class 2606 OID 41147)
-- Name: resume_experiences resume_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_experiences
    ADD CONSTRAINT resume_experiences_pkey PRIMARY KEY (id);


--
-- TOC entry 3483 (class 2606 OID 41149)
-- Name: resume_experiences_template resume_experiences_template_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_experiences_template
    ADD CONSTRAINT resume_experiences_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3491 (class 2606 OID 41151)
-- Name: resume_lines resume_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_lines_pkey PRIMARY KEY (id);


--
-- TOC entry 3493 (class 2606 OID 41153)
-- Name: resume_templates resume_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_templates
    ADD CONSTRAINT resume_templates_pkey PRIMARY KEY (id);


--
-- TOC entry 3498 (class 2606 OID 41155)
-- Name: resumes resumes_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);


--
-- TOC entry 3502 (class 2606 OID 41157)
-- Name: selected_application selected_application_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.selected_application
    ADD CONSTRAINT selected_application_pkey PRIMARY KEY (id);


--
-- TOC entry 3530 (class 2606 OID 66516)
-- Name: user_accounts unique_provider_account_id; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT unique_provider_account_id UNIQUE (provider, provider_account_id);


--
-- TOC entry 3532 (class 2606 OID 66509)
-- Name: user_accounts user_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 3504 (class 2606 OID 41159)
-- Name: user_custom_section_one user_custom_section_one_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_custom_section_one
    ADD CONSTRAINT user_custom_section_one_pkey PRIMARY KEY (id);


--
-- TOC entry 3506 (class 2606 OID 41161)
-- Name: user_custom_section_two user_custom_section_two_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_custom_section_two
    ADD CONSTRAINT user_custom_section_two_pkey PRIMARY KEY (id);


--
-- TOC entry 3509 (class 2606 OID 41163)
-- Name: user_education user_education_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_pkey PRIMARY KEY (id);


--
-- TOC entry 3513 (class 2606 OID 41165)
-- Name: user_skills user_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_pkey PRIMARY KEY (id);


--
-- TOC entry 3516 (class 2606 OID 41167)
-- Name: user_work_experience user_work_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_work_experience
    ADD CONSTRAINT user_work_experience_pkey PRIMARY KEY (id);


--
-- TOC entry 3520 (class 2606 OID 41169)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3522 (class 2606 OID 41171)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3524 (class 2606 OID 41281)
-- Name: views views_pkey; Type: CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.views
    ADD CONSTRAINT views_pkey PRIMARY KEY (slug);


--
-- TOC entry 3499 (class 1259 OID 41172)
-- Name: fki_application_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_application_id ON public.selected_application USING btree (application_id);


--
-- TOC entry 3500 (class 1259 OID 41173)
-- Name: fki_company_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_company_id_fkey ON public.selected_application USING btree (application_id);


--
-- TOC entry 3484 (class 1259 OID 41174)
-- Name: fki_resume_lines_user_education_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_resume_lines_user_education_id_fkey ON public.resume_lines USING btree (user_education_id);


--
-- TOC entry 3485 (class 1259 OID 41175)
-- Name: fki_resume_lines_user_skills_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_resume_lines_user_skills_id_fkey ON public.resume_lines USING btree (user_skills_id);


--
-- TOC entry 3486 (class 1259 OID 41176)
-- Name: fki_resume_lines_work_experience_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_resume_lines_work_experience_id_fkey ON public.resume_lines USING btree (work_experience_id);


--
-- TOC entry 3487 (class 1259 OID 41177)
-- Name: fki_resume_user_custom_section_one_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_resume_user_custom_section_one_id_fkey ON public.resume_lines USING btree (user_custom_section_one_id);


--
-- TOC entry 3488 (class 1259 OID 41178)
-- Name: fki_resume_user_custom_section_two_id_fkey; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_resume_user_custom_section_two_id_fkey ON public.resume_lines USING btree (user_custom_section_two_id);


--
-- TOC entry 3510 (class 1259 OID 41179)
-- Name: fki_user_skills_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX fki_user_skills_user_id ON public.user_skills USING btree (user_id);


--
-- TOC entry 3453 (class 1259 OID 66473)
-- Name: idx_applications_company_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_company_id ON public.applications USING btree (company_id);


--
-- TOC entry 3454 (class 1259 OID 66476)
-- Name: idx_applications_created_at; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_created_at ON public.applications USING btree (created_at);


--
-- TOC entry 3455 (class 1259 OID 66475)
-- Name: idx_applications_date_submitted; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_date_submitted ON public.applications USING btree (date_submitted);


--
-- TOC entry 3456 (class 1259 OID 66489)
-- Name: idx_applications_incomplete; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_incomplete ON public.applications USING btree (user_id) WHERE (is_complete = 'false'::text);


--
-- TOC entry 3457 (class 1259 OID 66490)
-- Name: idx_applications_posting_text_tsv; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_posting_text_tsv ON public.applications USING gin (to_tsvector('english'::regconfig, ((COALESCE(posting_text, ''::text) || ' '::text) || COALESCE(analyzed_posting_text, ''::text))));


--
-- TOC entry 3458 (class 1259 OID 66492)
-- Name: idx_applications_posting_url_trgm; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_posting_url_trgm ON public.applications USING gin (posting_url public.gin_trgm_ops);


--
-- TOC entry 3459 (class 1259 OID 66474)
-- Name: idx_applications_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_user_id ON public.applications USING btree (user_id);


--
-- TOC entry 3460 (class 1259 OID 66477)
-- Name: idx_applications_user_id_date_submitted; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_applications_user_id_date_submitted ON public.applications USING btree (user_id, date_submitted DESC);


--
-- TOC entry 3465 (class 1259 OID 66482)
-- Name: idx_companies_name_btree; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_companies_name_btree ON public.companies USING btree (name);


--
-- TOC entry 3466 (class 1259 OID 66491)
-- Name: idx_companies_name_trgm; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_companies_name_trgm ON public.companies USING gin (name public.gin_trgm_ops);


--
-- TOC entry 3467 (class 1259 OID 66481)
-- Name: idx_companies_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_companies_user_id ON public.companies USING btree (user_id);


--
-- TOC entry 3472 (class 1259 OID 66483)
-- Name: idx_cover_experiences_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_cover_experiences_user_id ON public.cover_experiences USING btree (user_id);


--
-- TOC entry 3479 (class 1259 OID 66484)
-- Name: idx_resume_experiences_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_resume_experiences_user_id ON public.resume_experiences USING btree (user_id);


--
-- TOC entry 3489 (class 1259 OID 66485)
-- Name: idx_resume_lines_resume_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_resume_lines_resume_id ON public.resume_lines USING btree (resume_id);


--
-- TOC entry 3494 (class 1259 OID 66479)
-- Name: idx_resumes_application_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_resumes_application_id ON public.resumes USING btree (application_id);


--
-- TOC entry 3495 (class 1259 OID 66480)
-- Name: idx_resumes_created_at; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_resumes_created_at ON public.resumes USING btree (created_at);


--
-- TOC entry 3496 (class 1259 OID 66478)
-- Name: idx_resumes_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_resumes_user_id ON public.resumes USING btree (user_id);


--
-- TOC entry 3507 (class 1259 OID 66488)
-- Name: idx_user_education_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_user_education_user_id ON public.user_education USING btree (user_id);


--
-- TOC entry 3511 (class 1259 OID 66486)
-- Name: idx_user_skills_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_user_skills_user_id ON public.user_skills USING btree (user_id);


--
-- TOC entry 3514 (class 1259 OID 66487)
-- Name: idx_user_work_experience_user_id; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_user_work_experience_user_id ON public.user_work_experience USING btree (user_id);


--
-- TOC entry 3517 (class 1259 OID 66494)
-- Name: idx_users_created_at; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_users_created_at ON public.users USING btree (created_at);


--
-- TOC entry 3518 (class 1259 OID 66493)
-- Name: idx_users_email_trgm; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX idx_users_email_trgm ON public.users USING gin (email public.gin_trgm_ops);


--
-- TOC entry 3533 (class 1259 OID 66518)
-- Name: user_accounts_provider_provider_account_id_index; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX user_accounts_provider_provider_account_id_index ON public.user_accounts USING btree (provider, provider_account_id);


--
-- TOC entry 3534 (class 1259 OID 66517)
-- Name: user_accounts_user_id_index; Type: INDEX; Schema: public; Owner: resume_wrangler_user
--

CREATE INDEX user_accounts_user_id_index ON public.user_accounts USING btree (user_id);


--
-- TOC entry 3549 (class 2620 OID 41180)
-- Name: applications update_applications_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_applications_updated_at BEFORE UPDATE ON public.applications FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3550 (class 2620 OID 41181)
-- Name: body_fonts update_body_fonts_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_body_fonts_updated_at BEFORE UPDATE ON public.body_fonts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3551 (class 2620 OID 41182)
-- Name: companies update_companies_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3552 (class 2620 OID 41183)
-- Name: cover_experience_lines update_cover_experience_lines_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_cover_experience_lines_updated_at BEFORE UPDATE ON public.cover_experience_lines FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3553 (class 2620 OID 41184)
-- Name: cover_experiences update_cover_experiences_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_cover_experiences_updated_at BEFORE UPDATE ON public.cover_experiences FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3569 (class 2620 OID 41310)
-- Name: cover_letter_templates update_cover_letter_templates_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_cover_letter_templates_updated_at BEFORE UPDATE ON public.cover_letter_templates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3554 (class 2620 OID 41185)
-- Name: cover_letters update_cover_letters_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_cover_letters_updated_at BEFORE UPDATE ON public.cover_letters FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3555 (class 2620 OID 41186)
-- Name: header_fonts update_header_fonts_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_header_fonts_updated_at BEFORE UPDATE ON public.header_fonts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3556 (class 2620 OID 41187)
-- Name: resume_colors update_resume_colors_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resume_colors_updated_at BEFORE UPDATE ON public.resume_colors FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3559 (class 2620 OID 41188)
-- Name: resume_lines update_resume_experience_lines_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resume_experience_lines_updated_at BEFORE UPDATE ON public.resume_lines FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3558 (class 2620 OID 41189)
-- Name: resume_experiences_template update_resume_experiences_template_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resume_experiences_template_updated_at BEFORE UPDATE ON public.resume_experiences_template FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3557 (class 2620 OID 41190)
-- Name: resume_experiences update_resume_experiences_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resume_experiences_updated_at BEFORE UPDATE ON public.resume_experiences FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3560 (class 2620 OID 41191)
-- Name: resume_templates update_resume_templates_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resume_templates_updated_at BEFORE UPDATE ON public.resume_templates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3561 (class 2620 OID 41192)
-- Name: resumes update_resumes_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_resumes_updated_at BEFORE UPDATE ON public.resumes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3562 (class 2620 OID 41193)
-- Name: selected_application update_selected_application_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_selected_application_updated_at BEFORE UPDATE ON public.selected_application FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3570 (class 2620 OID 66519)
-- Name: user_accounts update_user_accounts_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_accounts_updated_at BEFORE UPDATE ON public.user_accounts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3563 (class 2620 OID 41194)
-- Name: user_custom_section_one update_user_custom_section_one_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_custom_section_one_updated_at BEFORE UPDATE ON public.user_custom_section_one FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3564 (class 2620 OID 41195)
-- Name: user_custom_section_two update_user_custom_section_two_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_custom_section_two_updated_at BEFORE UPDATE ON public.user_custom_section_two FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3565 (class 2620 OID 41196)
-- Name: user_education update_user_education_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_education_updated_at BEFORE UPDATE ON public.user_education FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3566 (class 2620 OID 41197)
-- Name: user_skills update_user_skills_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_skills_updated_at BEFORE UPDATE ON public.user_skills FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3567 (class 2620 OID 41198)
-- Name: user_work_experience update_user_work_experience_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_user_work_experience_updated_at BEFORE UPDATE ON public.user_work_experience FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3568 (class 2620 OID 41199)
-- Name: users update_users_updated_at; Type: TRIGGER; Schema: public; Owner: resume_wrangler_user
--

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 3535 (class 2606 OID 41200)
-- Name: applications applications_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON UPDATE CASCADE;


--
-- TOC entry 3546 (class 2606 OID 41205)
-- Name: selected_application company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.selected_application
    ADD CONSTRAINT company_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3536 (class 2606 OID 41210)
-- Name: cover_experience_lines cover_experience_lines_cover_experience_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_experience_lines
    ADD CONSTRAINT cover_experience_lines_cover_experience_id_fkey FOREIGN KEY (cover_experience_id) REFERENCES public.cover_experiences(id) ON UPDATE CASCADE;


--
-- TOC entry 3537 (class 2606 OID 41215)
-- Name: cover_experience_lines cover_experience_lines_cover_letter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_experience_lines
    ADD CONSTRAINT cover_experience_lines_cover_letter_id_fkey FOREIGN KEY (cover_letter_id) REFERENCES public.cover_letters(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3538 (class 2606 OID 41220)
-- Name: cover_letters cover_letters_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.cover_letters
    ADD CONSTRAINT cover_letters_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3539 (class 2606 OID 41225)
-- Name: resume_lines resume_lines_resume_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_lines_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id) NOT VALID;


--
-- TOC entry 3540 (class 2606 OID 41230)
-- Name: resume_lines resume_lines_user_education_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_lines_user_education_id_fkey FOREIGN KEY (user_education_id) REFERENCES public.user_education(id) ON UPDATE CASCADE;


--
-- TOC entry 3541 (class 2606 OID 41235)
-- Name: resume_lines resume_lines_user_skills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_lines_user_skills_id_fkey FOREIGN KEY (user_skills_id) REFERENCES public.user_skills(id) ON UPDATE CASCADE;


--
-- TOC entry 3542 (class 2606 OID 41240)
-- Name: resume_lines resume_lines_work_experience_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_lines_work_experience_id_fkey FOREIGN KEY (work_experience_id) REFERENCES public.user_work_experience(id) ON UPDATE CASCADE;


--
-- TOC entry 3543 (class 2606 OID 41245)
-- Name: resume_lines resume_user_custom_section_one_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_user_custom_section_one_id_fkey FOREIGN KEY (user_custom_section_one_id) REFERENCES public.user_custom_section_one(id) ON UPDATE CASCADE;


--
-- TOC entry 3544 (class 2606 OID 41250)
-- Name: resume_lines resume_user_custom_section_two_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resume_lines
    ADD CONSTRAINT resume_user_custom_section_two_id_fkey FOREIGN KEY (user_custom_section_two_id) REFERENCES public.user_custom_section_two(id) ON UPDATE CASCADE;


--
-- TOC entry 3545 (class 2606 OID 41255)
-- Name: resumes resumes_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3548 (class 2606 OID 66510)
-- Name: user_accounts user_accounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 3547 (class 2606 OID 41260)
-- Name: user_skills user_skills_user_id; Type: FK CONSTRAINT; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3722 (class 3256 OID 41265)
-- Name: companies Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.companies USING (true);


--
-- TOC entry 3723 (class 3256 OID 41266)
-- Name: cover_experience_lines Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.cover_experience_lines USING (true);


--
-- TOC entry 3724 (class 3256 OID 41267)
-- Name: cover_experiences Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.cover_experiences USING (true);


--
-- TOC entry 3725 (class 3256 OID 41268)
-- Name: cover_letters Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.cover_letters USING (true);


--
-- TOC entry 3726 (class 3256 OID 41269)
-- Name: resume_experiences Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.resume_experiences USING (true);


--
-- TOC entry 3727 (class 3256 OID 41270)
-- Name: resume_experiences_template Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.resume_experiences_template USING (true);


--
-- TOC entry 3728 (class 3256 OID 41271)
-- Name: resume_lines Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.resume_lines USING (true);


--
-- TOC entry 3729 (class 3256 OID 41272)
-- Name: resumes Enable read access for all users; Type: POLICY; Schema: public; Owner: resume_wrangler_user
--

CREATE POLICY "Enable read access for all users" ON public.resumes USING (true);


--
-- TOC entry 3714 (class 0 OID 40968)
-- Dependencies: 220
-- Name: companies; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3715 (class 0 OID 40976)
-- Dependencies: 222
-- Name: cover_experience_lines; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.cover_experience_lines ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3716 (class 0 OID 40982)
-- Dependencies: 223
-- Name: cover_experiences; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.cover_experiences ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3717 (class 0 OID 40990)
-- Dependencies: 225
-- Name: cover_letters; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.cover_letters ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3718 (class 0 OID 41024)
-- Dependencies: 229
-- Name: resume_experiences; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resume_experiences ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3719 (class 0 OID 41032)
-- Dependencies: 231
-- Name: resume_experiences_template; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resume_experiences_template ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3720 (class 0 OID 41040)
-- Dependencies: 233
-- Name: resume_lines; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resume_lines ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3721 (class 0 OID 41057)
-- Dependencies: 235
-- Name: resumes; Type: ROW SECURITY; Schema: public; Owner: resume_wrangler_user
--

ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;

-- Completed on 2025-11-12 12:43:41

--
-- PostgreSQL database dump complete
--

