SET statement_timeout
= 0;
SET lock_timeout
= 0;
SET idle_in_transaction_session_timeout
= 0;
SET client_encoding
= 'UTF8';
SET standard_conforming_strings
= on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies
= false;
SET xmloption
= content;
SET client_min_messages
= warning;
SET row_security
= off;

SET default_tablespace
= '';

SET default_table_access_method
= heap;


-- Create Applications table

CREATE TABLE public.applications
(
    id bigint NOT NULL,
    posting_text text,
    is_complete boolean DEFAULT false,
    created_at timestamp
    with time zone DEFAULT timezone
    ('utc'::text, now
    ()) NOT NULL,
    date_submitted timestamp
    with time zone,
    job_position text,
    posting_url text,
    analyzed_posting_text text,
    company_id bigint,
    key_skills text
);

    ALTER TABLE public.applications OWNER TO testuser;

COMMENT ON TABLE public.applications IS 'Table of job applications';

    ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (
    SEQUENCE NAME public.applications_id_seq
    START
    WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Create Companies table